; MIIIME Universal Cleaner Configuration
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
AppName=MIIIME Universal Cleaner

[Settings]
RunAsAdmin=0
ShowFinishMsg=1

[Options]
LogLevel=0

[Advanced]
RetryLimit=10
RetryDelay=50
LogRotationSize=5242880

[CleanupExclude]
;01={Roaming}\MyApp\profile\prefs.js
;02={Roaming}\MyApp\profile\chrome

[CleanupDelete]
;01={Roaming}\MyApp\Cache
;02={Local}\MyApp\BrowserMetrics
